---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86183.
--- DateTime: 2025/8/16 14:33
---

if(redis.call('GET',KEYS[1])==ARGV[1])then
    return redis.call('DEL',KEYS[1])
end
return 0